name: Python and Pandoc PDFLaTeX Setup

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify the desired Python version, e.g., '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml  # Example: install required Python dependencies

    - name: Install Pandoc and TeX Live
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive-latex-recommended
        
    - name: Run Python script
      run: |
        python script.py

    - name: Convert Markdown to PDF
      run: |
        pandoc output.md -o output.pdf -V geometry:margin=1in -V papersize=a4paper -V fontsize=10pt

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v3
      with:
        name: output-pdf
        path: output.pdf
